{{- if .Values.nginxPrometheusExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: {{ .Values.nginxPrometheusExporter.port.name }}
{{- end }}
